version: '3.8'

services:
  web:
    image: php:7.2-apache
    container_name: yii1-app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mariadb:10.5
    container_name: yii1-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii1_todo
      MYSQL_USER: yii
      MYSQL_PASSWORD: yii
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
